services:
  - type: web
    name: fixed-pronos-backend
    env: node
    runtime: "node"
    region: frankfurt
    plan: starter
    buildCommand: |
      npm install --production=false
      npx prisma generate
      npx prisma migrate deploy --schema=./prisma/schema.prisma
      npx tsc --project tsconfig.json
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: UPLOAD_PATH
        value: ./uploads
    healthCheckPath: /health
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1
